version: "3.8"
services:

  backend:
    build:
      context: .././gfl-server
      dockerfile: Dockerfile
    container_name: backend
    image: backend
    ports:
      - 5000:5000

  frontend:
    build:
      context: .././gfl-client
      dockerfile: Dockerfile
    image: frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - 3000:3000

volumes:
  data:
  data2:
